alias ap='ansible-playbook'
alias ua='sudo apt-get update && sudo apt-get dist-upgrade -y'
alias k='keychain --clear --nogui ~/.ssh/id_rsa'
alias t='tmux new-session -As tdefault'
alias t='tmux new'
alias ta='tmux attach'
alias trails='tmux new-session -As trails'
alias ts='tmux kill-server'
