alias ap='ansible-playbook'
alias ua='sudo apt update && sudo apt dist-upgrade -y && sudo apt-get autoclean && sudo apt-get autoremove -y'
alias t='tmux new-session -As tdefault'
alias ta='tmux attach'
alias trails='tmux new-session -As trails'
alias ts='tmux kill-server'
alias bex='bundle exec rails'
