---
- hosts: localhost
  tasks:
  - name: symlink directories
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vim
      - tmux

  - name: symlink files
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vimrc
      - tmux.conf
      - gemrc
      - bash_aliases

  - name: install tmux plugins
    command: ~/.tmux/plugins/tpm/bin/install_plugins
    environment: 
      TMUX_PLUGIN_MANAGER_PATH: ~/.tmux/plugins/
