---
# git submodule update --init --recursive
- hosts: all
  vars:
    user: deploy
  tasks:
  - name: install dependencies
    apt: name={{ item }}
         update_cache=yes
         state=present
    with_items:
      - tmux
    sudo: yes
  - name: symlink directories
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vim
      - tmux
  - name: symlink files
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vimrc
      - tmux.conf
      - gemrc
      - bash_aliases
  - name: install vim plugins
    command: vim +PluginInstall +qall
  - name: install tmux plugins
    command: ~/.tmux/plugins/tpm/bin/install_plugins
