---
- hosts: localhost
  tasks:
  - name: symlink directories
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vim
      - tmux
  - name: symlink files
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vimrc
      - tmux.conf
      - gemrc
      - bash_aliases
  - name: submodules
    shell: git submodule update --init --recursive chdir=~/.dotfiles
  - name: install vim plugins
    command: vim +PlugInstall +qall
  - name: install tmux plugins
    command: ~/.tmux/plugins/tpm/bin/install_plugins
      environment: TMUX_PLUGIN_MANAGER_PATH=/home/deploy/.tmux/plugins
