---
- hosts: localhost
  tasks:
  - name: symlink directories
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vim
      - tmux

  - name: symlink files
    file: src=~/.dotfiles/{{ item }}
          dest=~/.{{ item }}
          force=yes state=link
    with_items:
      - vimrc
      - tmux.conf
      - gemrc
      - bash_aliases

  - name: submodules
    shell: git submodule update --init --recursive chdir=~/.dotfiles

  - name: install tmux plugins
    command: ~/.tmux/plugins/tpm/bin/install_plugins
    environment: 
      TMUX_PLUGIN_MANAGER_PATH: ~/.tmux/plugins/

  - name: clone rbenv
    git: repo=https://github.com/rbenv/rbenv.git
         dest=~/.rbenv

  - name: clone ruby-build
    git: repo=https://github.com/rbenv/ruby-build.git
         dest=~/.rbenv/plugins/ruby-build

  - name: install virtualenv for current user
    pip: name=virtualenv

  - name: copy
    copy:
      src: nvm.sh
      dest: ~/.nvm

